backend: 
  name: github
  repo: rick-saenz/gatsbynetlify

media_folder: static/assets
public_folder: /assets

collections: 
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created at, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }